# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackTheRack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for HackTheRack
  pod 'Cluster'
  pod 'ViewAnimator'
  pod 'Material'
  pod 'SCLAlertView'
  pod 'Kingfisher'

end
